### ISSUE TITLE
Integration of swagger

### ISSUE THREAD

**Issue by akhilmhdh** [tinkerhub/platform#12]
Swagger is a tool to test API's easily using Open API spec sheet in a webpage based GUI. This task involves integrating swagger to fastify server in such a way that, when visiting a particular URL in our server we could access swagger webpage and test our API.

Fastify community has developed plugin (link in ref) to generate swagger documentation from the schema definition we apply in fastify validation. 

Tasks
- [x] Understand what is swagger and open api specsheet
- [x] Install fasify-swagger plugin
- [x] Configure with our server
- [x] Able to access swagger instance

Ref:

1. [swagger](https://swagger.io/)
2. [open api spec](https://www.openapis.org/)
3. [swagger fastify plugin](https://github.com/fastify/fastify-swagger)

**Comment by reenphygeorge** [comment]
I'll do it
