### ISSUE TITLE
Prisma Integration

### ISSUE THREAD

**Issue by akhilmhdh** [tinkerhub/platform#3]
We have decided to use prisma as our ORM. 

So let's start integrating prisma in our system. As a starter lets go with SQLite as no one have experience with docker and move to psql as we get more matured. Its better to integrate prisma as plugin and then use it as service everywhere. Ref provided

Ref:
https://www.prisma.io/fastify

Checklist

- [x] Prisma npm library added
- [x] Prisma config initialized
- [x] Gitignore sqllite file created
- [x] Integration with fastify
- [x] A dumy table record to verify integration

**Comment by seramg** [comment]
i will do it

**Comment by akhilmhdh** [comment]
Closing as this was addressed in #10

**Comment by akhilmhdh** [comment]
My bad not yet closed on PR
