### ISSUE TITLE
user profile api

### ISSUE THREAD

**Issue by akhilmhdh** [tinkerhub/platform#35]
## Description

Authorization and authentication are executed by supertokens. Now we need to extend the user and have a profile section. User's must fill this profile section before using our spa. Profile api will contain all the data like school/college, job etc.

## Checklist

- [x] Database design for profile
- [x] Validate input data based on conditions
- [x] Endpoints for CRUD in profile
- [x] All the other API must be blocked till profile page is filled
- [x] A flag like verified should be given in profile page so that frontend can also block users in UI

Data can be found from design given in #33 or in join.tinkerhub.org.

**Comment by sreehari2003** [comment]
> ## Description
> Authorization and authentication are executed by supertokens. Now we need to extend the user and have a profile section. User's must fill this profile section before using our spa. Profile api will contain all the data like school/college, job etc.
> 
> ## Checklist
> * [ ]  Database design for profile
> * [ ]  Validate input data based on conditions
> * [ ]  Endpoints for CRUD in profile
> * [ ]  All the other API must be blocked till profile page is filled
> * [ ]  A flag like verified should be given in profile page so that frontend can also block users in UI
> 
> Data can be found from design given in #33 or in join.tinkerhub.org.

## these are the data needed from user
  ```
  type Form = {
  campus: string l;
  desc: string ;
  district: string ;
  dob: string ;
  email: string ;
  house: string ;
  mentor: string ;
  mobile: numberl;
  name: string l;
  pin:number;
 // enum maybe
  pronoun: string ;
  skills: string ;
  street: string;
};
```
@seramg
