### ISSUE TITLE
Restructure to move everything related to fastify/server to a seperate folder

### ISSUE THREAD

**Issue by akhilmhdh** [tinkerhub/platform#4]
Right now the project follows a components based folder structure in which contains various aspects related to a particular business logic like auth folder contains everything related to auth services to controller and routes.

I was thinking how about we move from that to something auth components contains only the functions or services for auth and move everthing to server related like middlewares, controllers, validation to a seperate folder like `server/http`. 

This would avoid mixing fastify types to be spread all over the components. Something that needs to be discussed later on?

**Comment by akhilmhdh** [comment]
@sreehari2003 can you start working on this. This will improve the way one organize there codebase

**Comment by sreehari2003** [comment]
so you want me to move all the middleware irrespective of their functions to a new folder ?  i actually didn't understood the assignment also don't you think that our current file structure is much more simpler ?

**Comment by sreehari2003** [comment]
ok i will do it
