### ISSUE TITLE
Docker for development

### ISSUE THREAD

**Issue by akhilmhdh** [tinkerhub/platform#6]
The development needs to move to a docker setup using docker-compose and docker/podman.

This will allow other people to also get started easily with simple commands. The docker compose for development should have the postgres and the server with live reloading by volume mount enabled.

Ref:

1. [Docker](https://www.docker.com/)
2. [Podman](https://podman.io/)
3. [Docker compose](https://docs.docker.com/compose/)
4. [Play with docker](https://www.docker.com/play-with-docker/)

Checklist
- [x] Docker file for running development server
- [x] Docker compose file for development containing the server build and psql
- [x] All the commands documented
- [x] Server should build in compose env on change

**Comment by reenphygeorge** [comment]
I'll do it :)

**Comment by akhilmhdh** [comment]
This ticket is in backlog now, because there is bug that is caused by prisma. Causing app startup to fail

**Comment by akhilmhdh** [comment]
This has been fixed when migrating from single to monorepo
