### ISSUE TITLE
Add Send OTP via phone

### ISSUE THREAD

**Issue by DarkPhoenix2704** [tinkerhub/platform#61]
Current implementation allows to send OTP only via SMS. Some numbers appears to be blacklisted and are not receiving the OTP message. 

So send OTP via Phone should be added

**Comment by sreehari2003** [comment]
> Current implementation allows to send OTP only via SMS. Some numbers appears to be blacklisted and are not receiving the OTP message.
> 
> So send OTP via Phone should be added

any docs that i can refer  ? it appers supertokens dont provide a feature to send otp via phone

**Comment by DarkPhoenix2704** [comment]
you have to modify the user context in the API for resend code before calling the original implementation and then read the userContext in the sendSms function to know if you should do it via a call or via SMS.

**Comment by DarkPhoenix2704** [comment]
Currently the emails are sent using One API in MSG91. 
If I'm right, we have to use SendOTP service for both SMS & CALL Verification

The [Jenga](https://github.com/tinkerhub/jenga/blob/master/jenga/services/msg91.py) currently in production uses this.

**Comment by sreehari2003** [comment]
> Currently the SMSs are sent using One API in MSG91. If I'm right, we have to use SendOTP service for both SMS & CALL Verification
> 
> The [Jenga](https://github.com/tinkerhub/jenga/blob/master/jenga/services/msg91.py) currently in production uses this.

I think we can implement this feature in version 1.0,  right now lets focus in launching the app

**Comment by DarkPhoenix2704** [comment]
> I think we can implement this feature in version 1.0, right now lets focus in launching the app

What is the point of launching something, when users couldn't login?😅
> 
> maybe try contributing this to the code @DarkPhoenix2704

yeah sure. Maybe i can work on this
